api_platform:
    title: OpenRoaming Portal API
    version: 1.7.3
    formats:
        jsonld: [ 'application/ld+json' ]
        json: [ 'application/json' ]
        yaml: [ 'application/yaml', 'text/yaml' ]
    docs_formats:
        jsonld: [ 'application/ld+json' ]
        json: [ 'application/json' ]
        yaml: [ 'application/yaml', 'text/yaml' ]
        html: [ 'text/html' ]
    defaults:
        stateless: true
        cache_headers:
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    swagger:
        versions: [ 3 ]
        api_keys:
            bearerAuth:
                name: Authorization
                type: header
        swagger_ui_extra_configuration:
            persistAuthorization: true
            filter: true
    use_symfony_listeners: true

    mapping:
        paths:
            - '%kernel.project_dir%/src/Api/V1/Entity'
            - '%kernel.project_dir%/src/Api/V2/Entity'
