doctrine:
    dbal:
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                server_version: '8.0.39'
            freeradius:
                url: '%env(resolve:DATABASE_FREERADIUS_URL)%'
                server_version: '8.0.39'
        default_connection: default


        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        controller_resolver:
            auto_mapping: true # Tells doctrine to automatically map entities in all registered bundles
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    App\Entity:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: Entity
            freeradius:
                connection: freeradius
                mappings:
                    App\RadiusDb\Entity:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/RadiusDb/Entity'
                        prefix: 'App\RadiusDb\Entity'
                        alias: EntityRadius


when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
