lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    user_identity_field: uuid
    token_ttl: 3600

    api_platform:
        check_path: /api/v1/auth/local
        username_path: uuid
        password_path: password