nbgrp_onelogin_saml:
    onelogin_settings:
        default:
            # Mandatory SAML settings
            idp:
                entityId: '@=service("App\\Service\\SamlProviderConfigService").getDefaultProviderConfig()["idpEntityId"]'
                singleSignOnService:
                    url: '@=service("App\\Service\\SamlProviderConfigService").getDefaultProviderConfig()["idpSsoUrl"]'
                    binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
                x509cert: '@=service("App\\Service\\SamlProviderConfigService").getDefaultProviderConfig()["idpX509Cert"]'
            sp:
                entityId: '@=service("App\\Service\\SamlProviderConfigService").getDefaultProviderConfig()["spEntityId"]'
                assertionConsumerService:
                    url: '@=service("App\\Service\\SamlProviderConfigService").getDefaultProviderConfig()["spAcsUrl"]'
                    binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
            security:
                allowRepeatAttributeName: true
            strict: false
            debug: false
