FROM ubuntu:22.04

# Set non-interactive environment variables
ENV DEBIAN_FRONTEND=noninteractive
ENV COMPOSER_ALLOW_SUPERUSER=1

# Update the package list and install necessary packages
RUN apt-get update && \
    apt-get install -y apt-utils wget curl nano zip unzip git openssl sqlite3 build-essential software-properties-common cron supervisor gnupg tzdata && \
    apt-get upgrade -y

RUN echo "UTC" >> /etc/timezone \
  && dpkg-reconfigure -f noninteractive tzdata

# Install FreeRADIUS and its dependencies
RUN apt-get install -y freeradius freeradius-mysql

# Copy FreeRADIUS configuration files
COPY freeradius_conf/radius.conf /etc/freeradius/3.0/mods-available/sql
COPY freeradius_conf/sql.conf /etc/freeradius/3.0/mods-available/sql
RUN ln -s /etc/freeradius/3.0/mods-available/sql /etc/freeradius/3.0/mods-enabled/sql

# Copy client configuration file
COPY freeradius_conf/clients.conf /etc/freeradius/3.0/clients.conf

# Copy default file to accept all realms to authenticate
COPY freeradius_conf/default /etc/freeradius/3.0/sites-enabled/default

# Copy the existing ca file
COPY signing-keys/ca.pem /etc/freeradius/3.0/certs/ca.pem

# Expose the default RADIUS ports
EXPOSE 1812/udp 1813/udp

# Start FreeRADIUS in the foreground when the container starts
CMD ["freeradius", "-X"]