version: '3'
services:
  web:
    image: registry.tetrapi.pt/tcs/cc/cc-openroaming-provisioning-web:1.3.1
    env_file:
      - .env
    volumes:
      - .env/:/var/www/openroaming/.env
      - ./pgp_public_keys/:/var/www/openroaming/pgp_public_keys/
      - ./signing-keys/:/var/www/openroaming/signing-keys/
      - uploads:/var/www/openroaming/public/resources/uploaded
      - ./service-config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./service-config/nginx/sites:/etc/nginx/conf.d:ro
      - ./service-config/supervisor/supervisord-dev.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    ports:
      - "80:80"
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: openroaming
      MYSQL_USER: openroaming
      MYSQL_PASSWORD: openroaming
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
  memcached:
    image: memcached

volumes:
  uploads:
      driver: local
  mysql:
    driver: local
