FROM ubuntu:22.04

# Set non-interactive environment variables
ENV DEBIAN_FRONTEND=noninteractive
ENV COMPOSER_ALLOW_SUPERUSER=1

# Update the package list and install necessary packages
RUN apt-get update && \
    apt-get install -y apt-utils wget curl nano zip unzip git openssl sqlite3 build-essential software-properties-common cron supervisor gnupg tzdata && \
    apt-get upgrade -y

RUN echo "UTC" >> /etc/timezone \
  && dpkg-reconfigure -f noninteractive tzdata

# Install FreeRADIUS and its dependencies
RUN apt-get install -y freeradius freeradius-mysql

# Copy FreeRADIUS configuration files
COPY freeradius_conf/radius.conf /etc/freeradius/3.0/mods-available/sql
COPY freeradius_conf/sql.conf /etc/freeradius/3.0/mods-available/sql
RUN ln -s /etc/freeradius/3.0/mods-available/sql /etc/freeradius/3.0/mods-enabled/sql

# Copy client configuration file
COPY freeradius_conf/clients.conf /etc/freeradius/3.0/clients.conf

# Generate a new CA key and certificate
RUN openssl genpkey -algorithm RSA -out /etc/freeradius/3.0/certs/ca.key
RUN openssl req -new -key /etc/freeradius/3.0/certs/ca.key -out /etc/freeradius/3.0/certs/ca.csr -subj "/CN=freeradius-ca"
RUN openssl x509 -req -days 365 -in /etc/freeradius/3.0/certs/ca.csr -signkey /etc/freeradius/3.0/certs/ca.key -out /etc/freeradius/3.0/certs/ca.pem

# Generate server key and certificate
RUN openssl req -newkey rsa:2048 -nodes -keyout /etc/freeradius/3.0/certs/server.key -out /etc/freeradius/3.0/certs/server.csr -subj "/CN=freeradius-server" && \
    openssl x509 -req -days 365 -in /etc/freeradius/3.0/certs/server.csr -CA /etc/freeradius/3.0/certs/ca.pem -CAkey /etc/freeradius/3.0/certs/ca.key -CAcreateserial -out /etc/freeradius/3.0/certs/server.pem

# Create the directory for realm configuration - Still in testing
RUN mkdir -p /etc/freeradius/3.0/mods-config/realm

# Configure realm to accept any realm - Still in testing
RUN echo 'realm NULL { format = "suffix" }' > /etc/freeradius/3.0/mods-config/realm/null

# Expose the default RADIUS ports
EXPOSE 1812/udp 1813/udp

# Start FreeRADIUS in the foreground when the container starts
CMD ["freeradius", "-X"]