version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/var/www/openroaming
      - ./pgp_public_keys/:/var/www/openroaming/pgp_public_keys/
      - ./service-config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./service-config/nginx/sites:/etc/nginx/conf.d:ro
      - ./service-config/supervisor/supervisord-dev.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    ports:
      - "80:80"
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: openroaming
      MYSQL_USER: openroaming
      MYSQL_PASSWORD: openroaming
    volumes:
      - mysql:/var/lib/mysql
  memcached:
    image: memcached
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - '1080:1080'
      - '1025:1025'

volumes:
  mysql:
    driver: local
