# This configuration generates the routes jsonLd format
api_platform_v1:
    resource: '%kernel.project_dir%/src/Api/V1/Entity'
    type: api_platform
    prefix: /api/v1
    defaults:
        _api_platform_resource_class_directories: [ '%kernel.project_dir%/src/Api/V1/Entity' ]
        _api_areas: ['v1']
        _format: jsonld

api_platform_v2:
    resource: '%kernel.project_dir%/src/Api/V2/Entity'
    type: api_platform
    prefix: /api/v2
    defaults:
        _api_platform_resource_class_directories: [ '%kernel.project_dir%/src/Api/V2/Entity' ]
        _api_areas: ['v2']
        _format: jsonld
