# This configuration generate the routes jsonLd format
api_platform_v1:
    resource: .
    type: api_platform
    prefix: /api/v1
    defaults:
        _api_areas: ['v1']
        _format: jsonld

api_platform_v2:
    resource: .
    type: api_platform
    prefix: /api/v2
    defaults:
        _api_areas: ['v2']
        _format: jsonld
