<?php

namespace App\Enum;

enum AdminPermissionsType: string
{
    // Users Management page
    case USERS_MANAGEMENT_WRITE = 'USERS_MANAGEMENT_WRITE';
    case USERS_MANAGEMENT_READ = 'USERS_MANAGEMENT_READ';
    case USERS_MANAGEMENT_NO_PERM = 'USERS_MANAGEMENT_NO_PERM';
    // Platform Status page
    case PLATFORM_STATUS_WRITE = 'PLATFORM_STATUS_WRITE';
    case PLATFORM_STATUS_READ = 'PLATFORM_STATUS_READ';
    case PLATFORM_STATUS_NO_PERM = 'PLATFORM_STATUS_NO_PERM';
    // Landing Page Configuration page
    case LANDING_PAGE_CONFIG_WRITE = 'LANDING_PAGE_CONFIG_WRITE';
    case LANDING_PAGE_CONFIG_READ = 'LANDING_PAGE_CONFIG_READ';
    case LANDING_PAGE_CONFIG_NO_PERM = 'LANDING_PAGE_CONFIG_NO_PERM';
    // User Engagement page
    case USER_ENGAGEMENT_WRITE = 'USER_ENGAGEMENT_WRITE';
    case USER_ENGAGEMENT_READ = 'USER_ENGAGEMENT_READ';
    case USER_ENGAGEMENT_NO_PERM = 'USER_ENGAGEMENT_NO_PERM';
    // Terms and Policies page
    case TERMS_POLICIES_WRITE = 'TERMS_POLICIES_WRITE';
    case TERMS_POLICIES_READ = 'TERMS_POLICIES_READ';
    case TERMS_POLICIES_NO_PERM = 'TERMS_POLICIES_NO_PERM';
    // CRON Schedule Automation page
    case CRON_SCHEDULE_WRITE = 'CRON_SCHEDULE_WRITE';
    case CRON_SCHEDULE_READ = 'CRON_SCHEDULE_READ';
    case CRON_SCHEDULE_NO_PERM = 'CRON_SCHEDULE_NO_PERM';
    // Authentication Methods page
    case AUTHENTICATION_METHODS_WRITE = 'AUTHENTICATION_METHODS_WRITE';
    case AUTHENTICATION_METHODS_READ = 'AUTHENTICATION_METHODS_READ';
    case AUTHENTICATION_METHODS_NO_PERM = 'AUTHENTICATION_METHODS_NO_PERM';
    // Two Factor Authenticator  page
    case TWO_FACTOR_AUTH_WRITE = 'TWO_FACTOR_AUTH_WRITE';
    case TWO_FACTOR_AUTH_READ = 'TWO_FACTOR_AUTH_READ';
    case TWO_FACTOR_AUTH_NO_PERM = 'TWO_FACTOR_AUTH_NO_PERM';
    // LDAP Synchronization  page
    case LDAP_SYNCHRONIZATION_WRITE = 'LDAP_SYNCHRONIZATION_WRITE';
    case LDAP_SYNCHRONIZATION_READ = 'LDAP_SYNCHRONIZATION_READ';
    case LDAP_SYNCHRONIZATION_NO_PERM = 'LDAP_SYNCHRONIZATION_NO_PERM';
    // Radius Profile Configuration  page
    case RADIUS_PROFILE_CONFIG_WRITE = 'RADIUS_PROFILE_CONFIG_WRITE';
    case RADIUS_PROFILE_CONFIG_READ = 'RADIUS_PROFILE_CONFIG_READ';
    case RADIUS_PROFILE_CONFIG_NO_PERM = 'RADIUS_PROFILE_CONFIG_NO_PERM';
    // SMS Configuration page
    case SMA_CONFIG_WRITE = 'SMA_CONFIG_WRITE';
    case SMA_CONFIG_READ = 'SMA_CONFIG_READ';
    case SMA_CONFIG_NO_PERM = 'SMA_CONFIG_NO_PERM';
    // Portal Statistics page
    case PORTAL_STATISTICS_WRITE = 'PORTAL_STATISTICS_WRITE';
    case PORTAL_STATISTICS_READ = 'PORTAL_STATISTICS_READ';
    case PORTAL_STATISTICS_NO_PERM = 'PORTAL_STATISTICS_NO_PERM';
    // Connectivity Statistics page
    case CONNECTIVITY_STATISTICS_WRITE = 'CONNECTIVITY_STATISTICS_WRITE';
    case CONNECTIVITY_STATISTICS_READ = 'CONNECTIVITY_STATISTICS_READ';
    case CONNECTIVITY_STATISTICS_NO_PERM = 'CONNECTIVITY_STATISTICS_NO_PERM';


}