<?php

declare(strict_types=1);

namespace App\Enum;

enum AnalyticalEventType: string
{
    case DOWNLOAD_PROFILE = 'DOWNLOAD_PROFILE';
    case USER_CREATION = 'USER_CREATION';
    case USER_VERIFICATION = 'USER_VERIFICATION';
    case USER_SMS_ATTEMPT = 'USER_SMS_ATTEMPT';
    case USER_ACCOUNT_UPDATE = 'USER_ACCOUNT_UPDATE';
    case USER_ACCOUNT_UPDATE_FROM_DASHBOARD = 'USER_ACCOUNT_UPDATE_FROM_DASHBOARD';
    case USER_ACCOUNT_UPDATE_PASSWORD = 'USER_ACCOUNT_UPDATE_PASSWORD';
    case USER_ACCOUNT_UPDATE_PASSWORD_FROM_DASHBOARD = 'USER_ACCOUNT_UPDATE_PASSWORD_FROM_DASHBOARD';
    case USER_ACCOUNT_DELETION = 'USER_ACCOUNT_DELETION';
    case SUPER_ADMIN_CREATION = 'SUPER_ADMIN_CREATION';
    case SUPER_ADMIN_VERIFICATION = 'SUPER_ADMIN_VERIFICATION';
    case ADMIN_CREATION = 'ADMIN_CREATION';
    case ADMIN_VERIFICATION = 'ADMIN_VERIFICATION';
    case ADMIN_CHANGED_LOGIN_WITH_UUID_ONLY = 'ADMIN_CHANGED_LOGIN_WITH_UUID_ONLY';
    case FORGOT_PASSWORD_EMAIL_REQUEST = 'FORGOT_PASSWORD_EMAIL_REQUEST';
    case FORGOT_PASSWORD_SMS_REQUEST = 'FORGOT_PASSWORD_SMS_REQUEST';
    case FORGOT_PASSWORD_REQUEST_ACCEPTED = 'FORGOT_PASSWORD_REQUEST_ACCEPTED';
    case LOGIN_TRADITIONAL_REQUEST = 'LOGIN_TRADITIONAL_REQUEST';
    case MICROSOFT_LOGIN_REQUEST = 'MICROSOFT_LOGIN_REQUEST';
    case GOOGLE_LOGIN_REQUEST = 'GOOGLE_LOGIN_REQUEST';
    case LOGOUT_REQUEST = 'LOGOUT_REQUEST';
    case EXPORT_USERS_TABLE_REQUEST = 'EXPORT_USERS_TABLE_REQUEST';
    case EXPORT_FREERADIUS_STATISTICS_REQUEST = 'EXPORT_FREERADIUS_STATISTICS_REQUEST';
    case EXPORT_ACTIVITY_LOGS_REQUEST = 'EXPORT_ACTIVITY_LOGS_REQUEST';
    case DELETED_USER_BY = 'DELETED_USER_BY';
    case SETTING_PAGE_STYLE_REQUEST = 'SETTING_PAGE_STYLE_REQUEST';
    case SETTING_PAGE_STYLE_RESET_REQUEST = 'SETTING_PAGE_STYLE_RESET_REQUEST';
    case SETTING_PLATFORM_STATUS_REQUEST = 'SETTING_PLATFORM_STATUS_REQUEST';
    case SETTING_PLATFORM_STATUS_RESET_REQUEST = 'SETTING_PLATFORM_STATUS_RESET_REQUEST';
    case SETTING_PLATFORM_2FA_REQUEST = 'SETTING_PLATFORM_2FA_REQUEST';
    case SETTING_PLATFORM_2FA_RESET_REQUEST = 'SETTING_PLATFORM_2FA_RESET_REQUEST';
    case SETTING_TERMS_REQUEST = 'SETTING_TERMS_REQUEST';

    case SETTING_MAP_REQUEST = 'SETTINGS_MAP_REQUEST';
    case SETTING_TERMS_RESET_REQUEST = 'SETTING_TERMS_RESET_REQUEST';
    case SETTING_RADIUS_CONF_REQUEST = 'SETTING_RADIUS_CONF_REQUEST';
    case SETTING_RADIUS_CONF_RESET_REQUEST = 'SETTING_RADIUS_CONF_RESET_REQUEST';
    case SETTING_AUTHS_CONF_REQUEST = 'SETTING_AUTHS_CONF_REQUEST';
    case SETTING_AUTHS_CONF_RESET_REQUEST = 'SETTING_AUTHS_CONF_RESET_REQUEST';
    case SETTING_LDAP_CONF_REQUEST = 'SETTING_LDAP_CONF_REQUEST';
    case SETTING_LDAP_CONF_RESET_REQUEST = 'SETTING_LDAP_CONF_RESET_REQUEST';
    case SETTING_CAPPORT_CONF_REQUEST = 'SETTING_CAPPORT_CONF_REQUEST';
    case SETTING_CAPPORT_CONF_RESET_REQUEST = 'SETTING_CAPPORT_CONF_RESET_REQUEST';
    case SETTING_SCHEDULE_CONF_REQUEST = 'SETTING_SCHEDULE_CONF_REQUEST';
    case SETTING_SCHEDULE_CONF_RESET_REQUEST = 'SETTING_SCHEDULE_CONF_RESET_REQUEST';
    case SETTING_RESET_CODE_REQUEST = 'SETTING_RESET_CODE_REQUEST';
    case SETTING_SMS_CONF_REQUEST = 'SETTING_SMS_CONF_REQUEST';
    case SETTING_SMS_CONF_CLEAR_REQUEST = 'SETTING_SMS_CONF_CLEAR_REQUEST';
    case SETTING_DOMAIN_BLACKLIST_REQUEST = 'SETTING_DOMAIN_BLACKLIST_REQUEST';
    case AUTH_LOCAL_API = 'AUTH_LOCAL_API';
    case AUTH_SAML_API = 'AUTH_SAML_API';
    case AUTH_GOOGLE_API = 'AUTH_GOOGLE_API';
    case AUTH_MICROSOFT_API = 'AUTH_MICROSOFT_API';
    case GET_USER_API = 'GET_USER_API';
    case USER_ACCOUNT_DELETION_API = 'USER_ACCOUNT_DELETION_API';
    case USER_ACCOUNT_PASSWORD_RESET_API = 'USER_ACCOUNT_PASSWORD_RESET_API';
    case USER_REVOKE_PROFILES = 'USER_REVOKE_PROFILES';
    case ADMIN_REVOKE_PROFILES = 'ADMIN_REVOKE_PROFILES';
    case CONFIG_PROFILE_ANDROID = 'CONFIG_PROFILE_ANDROID';
    case CONFIG_PROFILE_IOS = 'CONFIG_PROFILE_IOS';
    case ENABLE_LOCAL_2FA = 'ENABLE_LOCAL_2FA';
    case ENABLE_TOTP_2FA = 'ENABLE_TOTP_2FA';
    case DISABLE_2FA = 'DISABLE_2FA';
    case DISABLED_2FA_BY = 'DISABLED_2FA_BY';
    case VERIFY_TOTP_2FA = 'VERIFY_TOTP_2FA';
    case VERIFY_LOCAL_2FA = 'VERIFY_LOCAL_2FA';
    case VERIFY_OTP_2FA = 'VERIFY_OTP_2FA';
    case GENERATE_OTP_2FA = 'GENERATE_OTP_2FA';
    case TWO_FA_CODE_DISABLE = 'TWO_FA_CODE_DISABLE';
    case TWO_FA_CODE_ENABLE = 'TWO_FA_CODE_ENABLE';
    case TWO_FA_CODE_VERIFY = 'TWO_FA_CODE_VERIFY';
    case TWO_FA_CODE_DISABLE_RESEND = 'TWO_FA_CODE_DISABLE_RESEND';
    case TWO_FA_CODE_VALIDATE_RESEND = 'TWO_FA_CODE_VALIDATE_RESEND';
    case TWO_FA_CODE_VERIFY_RESEND = 'TWO_FA_CODE_VERIFY_RESEND';
    case TWO_FACTOR_AUTH_RESEND_INTERVAL = 'TWO_FACTOR_AUTH_RESEND_INTERVAL';
    case VERIFICATION_CODE_LOGIN_RESEND = 'VERIFICATION_CODE_LOGIN_RESEND';
    case USER_AUTO_DELETED = 'USER_AUTO_DELETED';
    case USER_AUTO_DELETE_CODE = 'USER_AUTO_DELETE_CODE';
    case AUTO_DELETE_UNCONFIRMED_ACCOUNTS = 'AUTO_DELETE_UNCONFIRMED_ACCOUNTS';
    case LOGIN_WITH_UUID_ONLY_LINK = 'LOGIN_WITH_UUID_ONLY_LINK';
    case LOGIN_WITH_UUID_ONLY_CODE = 'LOGIN_WITH_UUID_ONLY_CODE';
    case LOGIN_WITH_UUID_ONLY_CODE_RESEND = 'LOGIN_WITH_UUID_ONLY_CODE_RESEND';
    case LOGIN_WITH_UUID_ONLY_LOGIN = 'LOGIN_WITH_UUID_ONLY_LOGIN';
    case BLACKLIST_DOMAIN_ADDED = 'BLACKLIST_DOMAIN_ADDED';
    case BLACKLIST_DOMAIN_REMOVED = 'BLACKLIST_DOMAIN_REMOVED';
    case BLACKLIST_DOMAIN_EDITED = 'BLACKLIST_DOMAIN_EDITED';
    case BLACKLIST_SOURCE_ADDED = 'BLACKLIST_SOURCE_ADDED';
    case BLACKLIST_SOURCE_REMOVED = 'BLACKLIST_SOURCE_REMOVED';
    case BLACKLIST_SOURCE_ACTIVATED = 'BLACKLIST_SOURCE_ACTIVATED';
    case BLACKLIST_SOURCE_DEACTIVATED = 'BLACKLIST_SOURCE_DEACTIVATED';
    case BLACKLIST_SOURCES_MANUAL_REFRESH_ALL = 'BLACKLIST_SOURCES_MANUAL_REFRESH_ALL';
    case BLACKLIST_SOURCES_MANUAL_REFRESH = 'BLACKLIST_SOURCES_MANUAL_REFRESH';
    case BLACKLIST_SOURCES_COMMAND_REFRESH = 'BLACKLIST_SOURCES_COMMAND_REFRESH';
    case ADMIN_ADDED_PERMISSIONS = 'ADMIN_ADDED_PERMISSIONS';
    case ADMIN_REMOVED_PERMISSIONS = 'ADMIN_REMOVED_PERMISSIONS';
    case ADMIN_ADDED_NEW_USER = 'ADMIN_ADDED_NEW_USER';
    case INSTALLATION_ADMIN_CONFIRM_CODE_SENT = 'INSTALLATION_ADMIN_CONFIRM_CODE_SENT';
    case INSTALLATION_ADMIN_CONFIRM_CODE_RESENT = 'INSTALLATION_ADMIN_CONFIRM_CODE_RESENT';
    case CERTIFICATE_SETUP_PROCESS_CREATION = 'CERTIFICATE_SETUP_PROCESS_CREATION';
    case CERTIFICATE_SETUP_PROCESS_ABORTED = 'CERTIFICATE_SETUP_PROCESS_ABORTED';
    case CERTIFICATE_SETUP_PROCESS_RADSECPROXY_UPLOAD = 'CERTIFICATE_SETUP_PROCESS_RADSECPROXY_UPLOAD';
    case CERTIFICATE_SETUP_PROCESS_RADSECPROXY_CONFIG = 'CERTIFICATE_SETUP_PROCESS_RADSECPROXY_CONFIG';
    case CERTIFICATE_SETUP_PROCESS_RADSECPROXY_TEST = 'CERTIFICATE_SETUP_PROCESS_RADSECPROXY_TEST';
    case CERTIFICATE_SETUP_PROCESS_FREERADIUS_UPLOAD_MANUAL = 'CERTIFICATE_SETUP_PROCESS_FREERADIUS_UPLOAD_MANUAL';
    case CERTIFICATE_SETUP_PROCESS_FREERADIUS_UPLOAD_AUTO = 'CERTIFICATE_SETUP_PROCESS_FREERADIUS_UPLOAD_AUTO';
    case CERTIFICATE_SETUP_PROCESS_FREERADIUS_UPLOAD_AUTO_DOMAIN =
    'CERTIFICATE_SETUP_PROCESS_FREERADIUS_UPLOAD_AUTO_DOMAIN';
    case CERTIFICATE_SETUP_PROCESS_FREERADIUS_CONFIG = 'CERTIFICATE_SETUP_PROCESS_FREERADIUS_CONFIG';
    case CERTIFICATE_SETUP_PROCESS_FREERADIUS_TEST = 'CERTIFICATE_SETUP_PROCESS_FREERADIUS_TEST';
    case CERTIFICATE_SETUP_PROCESS_FREERADIUS_UPLOAD_CLOUDFLARE_DNS_CHALLENGE =
    'CERTIFICATE_SETUP_PROCESS_FREERADIUS_UPLOAD_CLOUDFLARE_DNS_CHALLENGE';
    case CERTIFICATE_SETUP_PROCESS_FREERADIUS_UPLOAD_CLOUDFLARE_HTTP_CHALLENGE =
    'CERTIFICATE_SETUP_PROCESS_FREERADIUS_UPLOAD_CLOUDFLARE_HTTP_CHALLENGE';
    case CERTIFICATE_VALIDATION_RAN = 'CERTIFICATE_VALIDATION_RAN';
    case INSTALLATION_DATABASE_CONFIG = 'INSTALLATION_DATABASE_CONFIG';
    case INSTALLATION_SETTINGS_CONFIG = 'INSTALLATION_SETTINGS_CONFIG';
    case INSTALLATION_SECURITY_TXT_CONFIG = 'INSTALLATION_SECURITY_TXT_CONFIG';
    case INSTALLATION_ADMIN_CONFIG = 'INSTALLATION_ADMIN_CONFIG';
    case INSTALLATION_COMMAND_CONFIG = 'INSTALLATION_COMMAND_CONFIG';
    case INSTALLATION_CONFIG_ABORTED = 'INSTALLATION_CONFIG_ABORTED';
    case INSTALLATION_IDENTITY_PASSWORD = 'INSTALLATION_IDENTITY_VERIFIED_CODE';
    case INSTALLATION_IDENTITY_VERIFIED_RESEND_CODE = 'INSTALLATION_IDENTITY_VERIFIED_RESEND_CODE';
    case INSTALLATION_IDENTITY_VERIFIED = 'INSTALLATION_IDENTITY_VERIFIED';
    case SYSTEM_RESET_REQUEST_STARTED = 'SYSTEM_RESET_REQUEST_STARTED';
    case SYSTEM_RESET_REQUEST_IN_PROGRESS = 'SYSTEM_RESET_REQUEST_IN_PROGRESS';
    case SYSTEM_RESET_REQUEST_COMPLETED = 'SYSTEM_RESET_REQUEST_COMPLETED';
    case CERTIFICATES_IDENTITY_PASSWORD = 'CERTIFICATES_IDENTITY_PASSWORD';
    case NOTIFY_ADMIN_EXPIRED_CERT = 'NOTIFY_ADMIN_EXPIRED_CERT';
    case NOTIFY_ADMIN_EXPIRING_CERT_ONE_DAY = 'NOTIFY_ADMIN_EXPIRING_CERT_ONE_DAY';
    case NOTIFY_ADMIN_EXPIRING_CERT_THREE_DAYS = 'NOTIFY_ADMIN_EXPIRING_CERT_THREE_DAYS';
    case NOTIFY_ADMIN_EXPIRING_CERT_WEEK = 'NOTIFY_ADMIN_EXPIRING_CERT_WEEK';
    case NOTIFY_ADMIN_EXPIRING_CERT_MONTH = 'NOTIFY_ADMIN_EXPIRING_CERT_MONTH';
    case NOTIFY_ADMIN_EXPIRING_CERT_TWO_MONTHS = 'NOTIFY_ADMIN_EXPIRING_CERT_TWO_MONTHS';
    case NOTIFY_ADMIN_EXPIRING_CERT_THREE_MONTHS = 'NOTIFY_ADMIN_EXPIRING_CERT_THREE_MONTHS';
    case RADIUS_TLS_UPDATED = 'RADIUS_TLS_UPDATED';
    case RETURN_APPS_UPDATED = 'RETURN_APPS_UPDATED';
    case RETURN_APPS_RESET_REQUEST = 'RETURN_APPS_RESET_REQUEST';
    case BREAKING_GLASS_ACCOUNT_GENERATION = 'BREAKING_GLASS_ACCOUNT_GENERATION';
    case BREAKING_GLASS_ACCOUNT_RESET = 'BREAKING_GLASS_ACCOUNT_RESET';
    case SMS_PROVIDER_CREATED = 'SMS_PROVIDER_CREATED';
    case SMS_PROVIDER_UPDATED = 'SMS_PROVIDER_UPDATED';
    case SMS_PROVIDER_DELETED = 'SMS_PROVIDER_DELETED';
    case SMS_PROVIDER_ACTIVATED = 'SMS_PROVIDER_ACTIVATED';
    case SMS_PROVIDER_DEACTIVATED = 'SMS_PROVIDER_DEACTIVATED';
    case SETTING_SECURITY_TXT_CONF_REQUEST = 'SETTING_SECURITY_TXT_CONF_REQUEST';

    public function getLabel(): string
    {
        return match ($this) {
            // User actions
            self::DOWNLOAD_PROFILE => 'Download Profile',
            self::USER_CREATION => 'User Created',
            self::USER_VERIFICATION => 'User Verified',
            self::USER_SMS_ATTEMPT => 'SMS Attempt',
            self::USER_ACCOUNT_UPDATE => 'User Account Updated',
            self::USER_ACCOUNT_UPDATE_FROM_DASHBOARD => 'User Account Updated (Dashboard)',
            self::USER_ACCOUNT_UPDATE_PASSWORD => 'User Password Updated',
            self::USER_ACCOUNT_UPDATE_PASSWORD_FROM_DASHBOARD => 'User Password Updated (Dashboard)',
            self::USER_ACCOUNT_DELETION => 'User Account Deleted',
            self::USER_AUTO_DELETED => 'User Account Auto-Deleted',
            self::USER_AUTO_DELETE_CODE => 'User Auto-Delete Code Sent',
            self::AUTO_DELETE_UNCONFIRMED_ACCOUNTS => 'Unconfirmed Accounts Deleted',
            self::USER_REVOKE_PROFILES => 'User Profiles Revoked',

            // Admin actions
            self::SUPER_ADMIN_CREATION => 'Super Admin Created',
            self::SUPER_ADMIN_VERIFICATION => 'Super Admin Verified',
            self::ADMIN_CREATION => 'Admin Created',
            self::ADMIN_VERIFICATION => 'Admin Verified',
            self::ADMIN_CHANGED_LOGIN_WITH_UUID_ONLY => 'Login UUID-Only Changed',
            self::ADMIN_ADDED_PERMISSIONS => 'Permissions Added',
            self::ADMIN_REMOVED_PERMISSIONS => 'Permissions Removed',
            self::ADMIN_ADDED_NEW_USER => 'Admin Added New User',
            self::ADMIN_REVOKE_PROFILES => 'Admin Revoked Profiles',
            self::DELETED_USER_BY => 'User Deleted',
            self::EXPORT_USERS_TABLE_REQUEST => 'Users Exported',
            self::EXPORT_FREERADIUS_STATISTICS_REQUEST => 'FreeRADIUS Stats Exported',

            // Auth events
            self::LOGIN_TRADITIONAL_REQUEST => 'Traditional Login',
            self::MICROSOFT_LOGIN_REQUEST => 'Microsoft Login',
            self::GOOGLE_LOGIN_REQUEST => 'Google Login',
            self::LOGOUT_REQUEST => 'Logout',
            self::FORGOT_PASSWORD_EMAIL_REQUEST => 'Forgot Password (Email)',
            self::FORGOT_PASSWORD_SMS_REQUEST => 'Forgot Password (SMS)',
            self::FORGOT_PASSWORD_REQUEST_ACCEPTED => 'Password Reset Accepted',
            self::LOGIN_WITH_UUID_ONLY_LINK => 'UUID Login Link',
            self::LOGIN_WITH_UUID_ONLY_CODE => 'UUID Login Code',
            self::LOGIN_WITH_UUID_ONLY_CODE_RESEND => 'UUID Login Code Resent',
            self::LOGIN_WITH_UUID_ONLY_LOGIN => 'UUID Login',
            self::VERIFICATION_CODE_LOGIN_RESEND => 'Verification Code Resent',

            // 2FA
            self::ENABLE_LOCAL_2FA => '2FA Enabled (Local)',
            self::ENABLE_TOTP_2FA => '2FA Enabled (TOTP)',
            self::DISABLE_2FA => '2FA Disabled',
            self::DISABLED_2FA_BY => '2FA Disabled by Admin',
            self::VERIFY_TOTP_2FA => '2FA Verified (TOTP)',
            self::VERIFY_LOCAL_2FA => '2FA Verified (Local)',
            self::VERIFY_OTP_2FA => '2FA Verified (OTP)',
            self::GENERATE_OTP_2FA => '2FA OTP Generated',
            self::TWO_FA_CODE_DISABLE => '2FA Code Disable',
            self::TWO_FA_CODE_ENABLE => '2FA Code Enable',
            self::TWO_FA_CODE_VERIFY => '2FA Code Verify',
            self::TWO_FA_CODE_DISABLE_RESEND => '2FA Disable Code Resent',
            self::TWO_FA_CODE_VALIDATE_RESEND => '2FA Validate Code Resent',
            self::TWO_FA_CODE_VERIFY_RESEND => '2FA Verify Code Resent',
            self::TWO_FACTOR_AUTH_RESEND_INTERVAL => '2FA Authentication Resend Interval',

            // Settings changes
            self::SETTING_PAGE_STYLE_REQUEST => 'Page Style Updated',
            self::SETTING_PAGE_STYLE_RESET_REQUEST => 'Page Style Reset',
            self::SETTING_PLATFORM_STATUS_REQUEST => 'Platform Status Updated',
            self::SETTING_PLATFORM_STATUS_RESET_REQUEST => 'Platform Status Reset',
            self::SETTING_PLATFORM_2FA_REQUEST => '2FA Settings Updated',
            self::SETTING_PLATFORM_2FA_RESET_REQUEST => '2FA Settings Reset',
            self::SETTING_TERMS_REQUEST => 'Terms Updated',
            self::SETTING_TERMS_RESET_REQUEST => 'Terms Reset',
            self::SETTING_RADIUS_CONF_REQUEST => 'RADIUS Config Updated',
            self::SETTING_RADIUS_CONF_RESET_REQUEST => 'RADIUS Config Reset',
            self::SETTING_AUTHS_CONF_REQUEST => 'Auth Methods Updated',
            self::SETTING_AUTHS_CONF_RESET_REQUEST => 'Auth Methods Reset',
            self::SETTING_LDAP_CONF_REQUEST => 'LDAP Config Updated',
            self::SETTING_LDAP_CONF_RESET_REQUEST => 'LDAP Config Reset',
            self::SETTING_CAPPORT_CONF_REQUEST => 'Captive Portal Updated',
            self::SETTING_CAPPORT_CONF_RESET_REQUEST => 'Captive Portal Reset',
            self::SETTING_SCHEDULE_CONF_REQUEST => 'Schedule Config Updated',
            self::SETTING_SCHEDULE_CONF_RESET_REQUEST => 'Schedule Config Reset',
            self::SETTING_RESET_CODE_REQUEST => 'Reset Code Requested',
            self::SETTING_SMS_CONF_REQUEST => 'SMS Config Updated',
            self::SETTING_SMS_CONF_CLEAR_REQUEST => 'SMS Config Cleared',
            self::SETTING_DOMAIN_BLACKLIST_REQUEST => 'Domain Blacklist Updated',

            // API
            self::AUTH_LOCAL_API => 'API Local Auth',
            self::AUTH_SAML_API => 'API SAML Auth',
            self::AUTH_GOOGLE_API => 'API Google Auth',
            self::AUTH_MICROSOFT_API => 'API Microsoft Auth',
            self::GET_USER_API => 'API Get User',
            self::USER_ACCOUNT_DELETION_API => 'API Account Deletion',
            self::USER_ACCOUNT_PASSWORD_RESET_API => 'API Password Reset',
            self::CONFIG_PROFILE_ANDROID => 'Android Profile Downloaded',
            self::CONFIG_PROFILE_IOS => 'iOS Profile Downloaded',

            // Domain Blacklist
            self::BLACKLIST_DOMAIN_ADDED => 'Domain Blacklisted',
            self::BLACKLIST_DOMAIN_REMOVED => 'Domain Removed from Blacklist',
            self::BLACKLIST_DOMAIN_EDITED => 'Blacklisted Domain Edited',
            self::BLACKLIST_SOURCE_ADDED => 'Blacklist Source Added',
            self::BLACKLIST_SOURCE_REMOVED => 'Blacklist Source Removed',
            self::BLACKLIST_SOURCE_ACTIVATED => 'Blacklist Source Activated',
            self::BLACKLIST_SOURCE_DEACTIVATED => 'Blacklist Source Deactivated',
            self::BLACKLIST_SOURCES_MANUAL_REFRESH_ALL => 'All Blacklist Sources Refreshed',
            self::BLACKLIST_SOURCES_MANUAL_REFRESH => 'Blacklist Source Refreshed',
            self::BLACKLIST_SOURCES_COMMAND_REFRESH => 'Blacklist Source Refreshed (Command)',

            // Certificates
            self::CERTIFICATE_SETUP_PROCESS_CREATION => 'Certificate Process Started',
            self::CERTIFICATE_SETUP_PROCESS_ABORTED => 'Certificate Process Aborted',
            self::CERTIFICATE_SETUP_PROCESS_RADSECPROXY_UPLOAD => 'RadSec Certificate Uploaded',
            self::CERTIFICATE_SETUP_PROCESS_RADSECPROXY_CONFIG => 'RadSec Certificate Configured',
            self::CERTIFICATE_SETUP_PROCESS_RADSECPROXY_TEST => 'RadSec Certificate Tested',
            self::CERTIFICATE_SETUP_PROCESS_FREERADIUS_UPLOAD_MANUAL => 'FreeRADIUS Certificate Uploaded (Manual)',
            self::CERTIFICATE_SETUP_PROCESS_FREERADIUS_UPLOAD_AUTO => 'FreeRADIUS Certificate Uploaded (Auto)',
            self::CERTIFICATE_SETUP_PROCESS_FREERADIUS_UPLOAD_AUTO_DOMAIN => 'FreeRADIUS Certificate Domain Uploaded',
            self::CERTIFICATE_SETUP_PROCESS_FREERADIUS_CONFIG => 'FreeRADIUS Certificate Configured',
            self::CERTIFICATE_SETUP_PROCESS_FREERADIUS_TEST => 'FreeRADIUS Certificate Tested',
            self::CERTIFICATE_SETUP_PROCESS_FREERADIUS_UPLOAD_CLOUDFLARE_DNS_CHALLENGE => 'Cloudflare DNS Challenge',
            self::CERTIFICATE_SETUP_PROCESS_FREERADIUS_UPLOAD_CLOUDFLARE_HTTP_CHALLENGE => 'Cloudflare HTTP Challenge',
            self::CERTIFICATE_VALIDATION_RAN => 'Certificate Validation Ran',
            self::CERTIFICATES_IDENTITY_PASSWORD => 'Certificate Identity Code Sent',

            // Installation
            self::INSTALLATION_DATABASE_CONFIG => 'Installation: Database Config',
            self::INSTALLATION_SETTINGS_CONFIG => 'Installation: Settings Config',
            self::INSTALLATION_SECURITY_TXT_CONFIG => 'Installation: Security Txt Config',
            self::INSTALLATION_ADMIN_CONFIG => 'Installation: Admin Config',
            self::INSTALLATION_COMMAND_CONFIG => 'Installation: Commands Config',
            self::INSTALLATION_CONFIG_ABORTED => 'Installation: Aborted',
            self::INSTALLATION_ADMIN_CONFIRM_CODE_SENT => 'Installation: Confirm Code Sent',
            self::INSTALLATION_ADMIN_CONFIRM_CODE_RESENT => 'Installation: Confirm Code Resent',
            self::INSTALLATION_IDENTITY_PASSWORD => 'Installation: Identity Code Sent',
            self::INSTALLATION_IDENTITY_VERIFIED_RESEND_CODE => 'Installation: Identity Code Resent',
            self::INSTALLATION_IDENTITY_VERIFIED => 'Installation: Identity Verified',

            // System
            self::SYSTEM_RESET_REQUEST_STARTED => 'System Reset Started',
            self::SYSTEM_RESET_REQUEST_IN_PROGRESS => 'System Reset In Progress',
            self::SYSTEM_RESET_REQUEST_COMPLETED => 'System Reset Completed',

            // Notifications
            self::NOTIFY_ADMIN_EXPIRED_CERT => 'Admin Notified: Expired Certificate',
            self::NOTIFY_ADMIN_EXPIRING_CERT_ONE_DAY => 'Admin Notified: Certificate Expires in 1 Day',
            self::NOTIFY_ADMIN_EXPIRING_CERT_THREE_DAYS => 'Admin Notified: Certificate Expires in 3 Days',
            self::NOTIFY_ADMIN_EXPIRING_CERT_WEEK => 'Admin Notified: Certificate Expires in 1 Week',
            self::NOTIFY_ADMIN_EXPIRING_CERT_MONTH => 'Admin Notified: Certificate Expires in 1 Month',
            self::NOTIFY_ADMIN_EXPIRING_CERT_TWO_MONTHS => 'Admin Notified: Certificate Expires in 2 Months',
            self::NOTIFY_ADMIN_EXPIRING_CERT_THREE_MONTHS => 'Admin Notified: Certificate Expires in 3 Months',

            // SMS
            self::SMS_PROVIDER_CREATED => 'SMS Provider Created',
            self::SMS_PROVIDER_UPDATED => 'SMS Provider Updated',
            self::SMS_PROVIDER_DELETED => 'SMS Provider Deleted',
            self::SMS_PROVIDER_ACTIVATED => 'SMS Provider Activated',
            self::SMS_PROVIDER_DEACTIVATED => 'SMS Provider Deactivated',

            // Other
            self::RADIUS_TLS_UPDATED => 'RADIUS TLS Updated',
            self::RETURN_APPS_UPDATED => 'Return Apps Updated',
            self::RETURN_APPS_RESET_REQUEST => 'Return Apps Reset',
            self::BREAKING_GLASS_ACCOUNT_GENERATION => 'Breaking Glass Account Generation',
            self::BREAKING_GLASS_ACCOUNT_RESET => 'Breaking Glass Account Reset',
            self::EXPORT_ACTIVITY_LOGS_REQUEST => 'Export Activity Logs Request',
            self::SETTING_MAP_REQUEST => 'Settings Map Request',
            self::SETTING_SECURITY_TXT_CONF_REQUEST => 'Security Tx Conflict Request',
        };
    }
}
