<?php

namespace App\Enum;

enum UserRadiusProfileRevokeReason: string
{
    case PROFILE_EXPIRED = 'PROFILE_EXPIRED';
    case LDAP_UNKNOWN_USER = 'LDAP_UNKNOWN_USER';
    case LDAP_USER_LOCKED = 'USER_LOCKED';
    case LDAP_USER_PASSWORD_EXPIRED = 'USER_PASSWORD_EXPIRED';
    case SAML_PROVIDER_DELETED = 'SAML_PROVIDER_DELETED';
    case USER_REVOKED_PROFILE = 'USER_REVOKED_PROFILE';
    case ADMIN_REVOKED_PROFILE = 'ADMIN_REVOKED_PROFILE';
    case ADMIN_BANNED_USER = 'ADMIN_BANNED_USER';
    case ADMIN_REMOVED_USER_VERIFICATION = 'ADMIN_REMOVED_USER_VERIFICATION';
    case USER_ACCOUNT_DELETED = 'USER_ACCOUNT_DELETED';
}
