controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
nbgrp_saml:
    resource: "@NbgrpOneloginSamlBundle/Resources/config/routes.php"
app_login:
    path: /login/{type}
    controller: App\Controller\SecurityController::login
    defaults:
        type: user

api_v1:
    prefix: /api/v1
    resource: '../src/Api/V1/Controller/'
    type: attribute

api_get_current_user:
    path: /api/v1/user
    controller: App\Api\V1\Controller\GetCurrentUserController::getCurrentUser
    methods: [ 'GET' ]

api_auth_local:
    path: /api/v1/auth/local
    controller: App\Api\V1\Controller\AuthController::authLocal
    methods: [ 'POST' ]

api_auth_saml:
    path: /api/v1/auth/saml
    controller: App\Api\V1\Controller\AuthController::authSaml
    methods: [ 'POST' ]

api_auth_google:
    path: /api/v1/auth/google
    controller: App\Api\V1\Controller\AuthController::authGoogle
    methods: [ 'POST' ]

api_auth_microsoft:
    path: /api/v1/auth/microsoft
    controller: App\Api\V1\Controller\AuthController::authMicrosoft
    methods: ['POST']

api_auth_local_register:
    path: /api/v1/auth/local/register
    controller: App\Api\V1\Controller\RegistrationController::localRegister
    methods: [ 'POST' ]

api_auth_local_reset:
    path: /api/v1/auth/local/reset
    controller: App\Api\V1\Controller\RegistrationController::localReset
    methods: [ 'POST' ]

api_auth_sms_register:
    path: /api/v1/auth/sms/register
    controller: App\Api\V1\Controller\RegistrationController::smsRegister
    methods: [ 'POST' ]

api_auth_sms_reset:
    path: /api/v1/auth/sms/reset
    controller: App\Api\V1\Controller\RegistrationController::smsReset
    methods: [ 'POST' ]

api_turnstile_html_android:
    path: /api/v1/turnstile/android
    controller: App\Api\V1\Controller\TurnstileController::getHtmlFromFile
    methods: [ 'GET' ]

api_config_profile_android:
    path: /api/v1/config/profile/android
    controller: App\Api\V1\Controller\ProfileController::getProfileAndroid
    methods: [ 'GET' ]

api_config_profile_ios:
    path: /api/v1/config/profile/ios
    controller: App\Api\V1\Controller\ProfileController::getProfileIos
    methods: [ 'GET' ]
