controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
nbgrp_saml:
        resource: "@NbgrpOneloginSamlBundle/Resources/config/routes.php"

api_v1:
    prefix: /api/v1
    resource: '../src/Api/V1/Controller/'
    type: annotation

api_auth_local:
    path: /api/v1/auth/local
    controller: App\Api\V1\Controller\AuthsController::authLocal
    methods: ['POST']

api_auth_saml:
    path: /api/v1/auth/saml
    controller: App\Api\V1\Controller\AuthsController::authSaml
    methods: ['POST']

api_auth_google:
    path: /api/v1/auth/google
    controller: App\Api\V1\Controller\AuthsController::authGoogle
    methods: ['POST']

api_auth_local_register:
    path: /api/v1/auth/local/register/
    controller: App\Api\V1\Controller\RegistrationController::localRegister
    methods: ['POST']

api_auth_local_reset:
    path: /api/v1/auth/local/reset/
    controller: App\Api\V1\Controller\RegistrationController::localReset
    methods: ['POST']

api_auth_sms_register:
    path: /api/v1/auth/sms/register/
    controller: App\Api\V1\Controller\RegistrationController::smsRegister
    methods: ['POST']

api_auth_sms_reset:
    path: /api/v1/auth/sms/reset/
    controller: App\Api\V1\Controller\RegistrationController::smsReset
    methods: ['POST']
