controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
nbgrp_saml:
        resource: "@NbgrpOneloginSamlBundle/Resources/config/routes.php"

api_v1:
    prefix: /api/v1
    resource: '../src/Api/V1/Controller/'
    type: annotation

api_login_check:
    path: /api/login_check
    methods: ['POST']