controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
nbgrp_saml:
    resource: "@NbgrpOneloginSamlBundle/Resources/config/routes.php"

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_dashboard_login:
    path: /dashboard/login
    controller: App\Controller\SecurityController::dashboardLogin

# API V1
api_v1:
    prefix: /api/v1
    resource: '../src/Api/V1/Controller/'
    type: attribute

# API V2
api_v2:
    prefix: /api/v2
    resource: '../src/Api/V2/Controller/'
    type: attribute
