controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
nbgrp_saml:
        resource: "@NbgrpOneloginSamlBundle/Resources/config/routes.php"

api_v1:
    prefix: /api/v1
    resource: '../src/Api/V1/Controller/'
    type: annotation

api_auth_local:
    path: /api/v1/auth/local
    methods: ['POST']

api_auth_saml:
    path: /api/v1/auth/saml
    controller: App\Api\V1\Controller\GenerateTokenController::generateJwtToken
    methods: ['POST']

api_get_current_user:
    path: /api/v1/user
    methods: ['GET']

api_auth_local_register:
    path: /api/v1/auth/local/register/
    controller: App\Api\V1\Controller\LocalRegistrationController::register
    methods: ['POST']