# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.email_address: '%env(EMAIL_ADDRESS)%'
    app.sender_name: '%env(SENDER_NAME)%'
services:
    #Things to make the login with Google work
    App\Controller\GoogleController:
      arguments:
        $clientRegistry: '@KnpU\OAuth2ClientBundle\Client\Provider\GoogleClient'
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    saml_user_factory:
        class: Nbgrp\OneloginSamlBundle\Security\User\SamlUserFactory
        arguments:
            ##  User class
            - App\Entity\User
            ##  Attribute mapping
            - password: 'notused'
              email: $email
              first_name: $givenName
              last_name: $surname
              uuid: $sAMAccountName
              saml_identifier: $sAMAccountName
              roles: []
